apiVersion: v1
kind: Service
metadata:
  name: cliserv
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cliserv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliserv
  template:
    metadata:
      labels:
        app: cliserv
    spec:
      containers:
      - name: cliserv
        image: mylandmax/kubwebtest:phpv1
        ports:
        - containerPort: 80