apiVersion: v1
kind: Service
metadata:
  name: picalc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: picalc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: picalc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picalc
  template:
    metadata:
      labels:
        app: picalc
    spec:
      containers:
      - name: picalc
        image: mylandmax/kubwebtest:picalv1
        ports:
        - containerPort: 80